### PR TITLE
Calculator doesn't work properly #1

### PR DESCRIPTION
**Pull request by devmaaj**
Fix issue: Calculator doesn't work properly https://github.com/vishalps2606/DesktopCalculator/issues/1

Del-> boolean vars and choicebox listener,
Add-> choicebox value validation on calculate method

When choicebox is loaded and default value "ADD" is added to choicebox value props nothing happens to validate this value and it is causing a invalid calculate method call because there is no choicebox value recognized until you do that for the first time.

I've deleted the choicebox listener because it cannot validate default value and move the validation to inside of calculate method getting the choicebox value props directly

### CODE REVIEW

**Review by vishalps2606 — CHANGES_REQUESTED** [review]
Everything is fine. You have done a fabulous job but I have an issue there, in the ChoiceBox element 'modulus' you have programmed it as 'percentage'. So whether make the value as 'PERCENTAGE' or make the program according to 'MODULUS' or add another element of choicebox. with the name of percentage. 

Thank you!

**Comment by devmaaj** [comment]
Oh my bad, i fixed it

**Review by vishalps2606 — APPROVED** [review]
Excellent work @vmaffioli!

**Comment by devmaaj** [comment]
thank you for oportunity!

**Pull request merged**
